#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_rubicon_plus_plus = env_modules.Clone()

env_rubicon_plus_plus.add_source_files(env.modules_sources, "*.cpp")
env_rubicon_plus_plus.add_source_files(env.modules_sources, "./core/*.cpp")
env_rubicon_plus_plus.add_source_files(env.modules_sources, "./core/chart/*.cpp")

