#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_rubicon_engine = env_modules.Clone()

# Rubicom
env_rubicon_engine.add_source_files(env.modules_sources, "*.cpp")

# Rubicon.Data
env_rubicon_engine.add_source_files(env.modules_sources, "data/*.cpp")

# Rubicon.Environment
# i aint fixin dat shit
# env_rubicon.add_source_files(env.modules_sources, "environment/*.cpp")
env_rubicon_engine.add_source_files(env.modules_sources, "environment/rubicon_dancer_controller.cpp")

# Add more like this here for more namespaces n stuff
# env_rubicon.add_source_files(env.modules_sources, "./environment/*.cpp")

